package my.cheysoff.desktop.store

import java.nio.file.Path
import java.sql.Connection
import java.sql.DriverManager

/** One row of `records`, exactly as it sits on disk. */
data class StoredRecord(
    val blindedId: String,
    val envelope: ByteArray,
    /** True when this device holds a version the server has not acknowledged. */
    val dirty: Boolean,
    /** The `seq` the server last gave this record, or null if the server has no version of it. */
    val lastSyncedSeq: Long?,
) {
    // Generated by hand because `envelope` is an array: the data-class versions would compare it by
    // identity, so two rows read from the same table in two queries would never be equal. Nothing
    // depends on this today, and that is the problem -- an equality that is wrong only in the case
    // nobody has written yet is a bug waiting for its first caller.
    override fun equals(other: Any?): Boolean = other is StoredRecord &&
        blindedId == other.blindedId &&
        envelope.contentEquals(other.envelope) &&
        dirty == other.dirty &&
        lastSyncedSeq == other.lastSyncedSeq

    override fun hashCode(): Int {
        var result = blindedId.hashCode()
        result = 31 * result + envelope.contentHashCode()
        result = 31 * result + dirty.hashCode()
        result = 31 * result + (lastSyncedSeq?.hashCode() ?: 0)
        return result
    }
}

/**
 * The desktop's local store: the server's table, on this machine.
 *
 * ```sql
 * records(blinded_id TEXT PRIMARY KEY, envelope BLOB, dirty INTEGER, last_synced_seq INTEGER)
 * ```
 *
 * That is the same shape `server/.../SyncStore.kt` holds, and holding it here rather than a
 * notes/folders schema is the design decision this whole module is built around. Two things follow
 * and both are the reason:
 *
 *  1. **At-rest security on desktop equals on-the-wire security.** A row is a `RecordEnvelope`:
 *     AES-256-GCM under a per-record key derived from `K_content`. Someone who copies `records.db`
 *     off the machine has exactly what the server operator has, and the server operator is the
 *     adversary this protocol was designed against. There is no SQLCipher here and none is needed;
 *     a file-level cipher would be a second, weaker layer over content that is already sealed.
 *  2. **The desktop is a sync replica by construction.** When the sync engine arrives it pushes
 *     these rows and stores what it pulls into these rows. Nothing translates between a local
 *     schema and a wire format, so there is no translation to get wrong -- and no second place
 *     where a field can be dropped.
 *
 * ## What it costs
 *
 * **No SQL over note content.** `WHERE title LIKE ?` is not expressible: the server cannot read
 * these rows and neither can SQLite. Search, sort and filter all happen in memory over decrypted
 * records, which is why [RecordNotesRepository] decrypts everything at unlock and serves reads from
 * a snapshot.
 *
 * **Everything is decrypted at unlock.** Opening the vault is O(number of records): one HKDF and
 * one AES-GCM open each, plus 4 KiB of padding stripped per record. Measured on the development
 * machine at roughly 30 microseconds per record, so a thousand notes is about 30 ms and ten
 * thousand about a third of a second — still under the threshold where a progress indicator is
 * needed. The memory cost is the sharper limit: every note's plaintext is resident for the whole
 * session, so ten thousand notes averaging 2 KB is around 20 MB of heap, and a hundred thousand is
 * 200 MB plus the padding overhead of reading them.
 *
 * **Where this stops being fine** is therefore somewhere around the tens of thousands of notes, and
 * the fix when it comes is not a different table: it is decrypting lazily and keeping an in-memory
 * index of just the fields the list screen shows. That change is local to
 * [RecordNotesRepository]; this class does not need to know.
 *
 * ## Threading
 *
 * One connection, and callers must serialise their own access — [RecordNotesRepository] does it
 * with a mutex. SQLite handles concurrent readers but this class deliberately does not hand out a
 * connection pool: the store is behind a repository whose writes are already serialised, and a pool
 * would only add a way for two writes to interleave.
 */
class RecordStore private constructor(private val connection: Connection) : AutoCloseable {

    companion object {
        /** Opens (creating if needed) the store at [path]. */
        fun open(path: Path): RecordStore {
            val store = RecordStore(DriverManager.getConnection("jdbc:sqlite:${path.toAbsolutePath()}"))
            store.migrate()
            return store
        }

        /**
         * An in-memory store, for tests.
         *
         * Named rather than `:memory:` so that the connection this returns is the only one that can
         * reach it; a plain `:memory:` database would be a fresh empty one for every connection,
         * which hides exactly the bugs a store test is looking for.
         */
        fun inMemory(name: String): RecordStore {
            val store = RecordStore(
                DriverManager.getConnection("jdbc:sqlite:file:$name?mode=memory&cache=shared"),
            )
            store.migrate()
            return store
        }
    }

    private fun migrate() {
        connection.createStatement().use { statement ->
            statement.executeUpdate(
                """
                CREATE TABLE IF NOT EXISTS records (
                    blinded_id TEXT PRIMARY KEY,
                    envelope BLOB NOT NULL,
                    dirty INTEGER NOT NULL,
                    last_synced_seq INTEGER
                )
                """.trimIndent(),
            )
            // Nullable, and NULL rather than 0 means "the server has no version of this record".
            // The phone spells the same state as 0 because its column is NOT NULL; the difference
            // is invisible to the protocol -- `seq` is the server's own counter and starts at 1 --
            // and NULL is the more honest spelling for a column that is genuinely absent.
        }
    }

    /** Every row. The only read: a session decrypts all of them at unlock. */
    fun readAll(): List<StoredRecord> {
        val rows = mutableListOf<StoredRecord>()
        connection.createStatement().use { statement ->
            statement.executeQuery(
                "SELECT blinded_id, envelope, dirty, last_synced_seq FROM records",
            ).use { results ->
                while (results.next()) {
                    val blindedId = results.getString(1)
                    val envelope = results.getBytes(2)
                    val dirty = results.getInt(3) != 0
                    val seq = results.getLong(4)
                    // `wasNull()` reports on the column read LAST, so it has to be asked
                    // immediately after `getLong(4)` and not after any other read. JDBC returns 0
                    // for a SQL NULL, and 0 versus "the server has no version of this record" are
                    // different states here.
                    val lastSyncedSeq = if (results.wasNull()) null else seq
                    rows += StoredRecord(blindedId, envelope, dirty, lastSyncedSeq)
                }
            }
        }
        return rows
    }

    /**
     * Inserts or replaces the record [blindedId], marking it dirty.
     *
     * `last_synced_seq` is left alone on an update, and that is the same rule `NoteDao.upsertNote`
     * follows for the same reason: it is the baseline the next push is built on, and resetting it
     * would tell the server that an already-uploaded record must not exist.
     */
    fun put(blindedId: String, envelope: ByteArray) {
        connection.prepareStatement(
            """
            INSERT INTO records (blinded_id, envelope, dirty, last_synced_seq)
            VALUES (?, ?, 1, NULL)
            ON CONFLICT(blinded_id) DO UPDATE SET envelope = excluded.envelope, dirty = 1
            """.trimIndent(),
        ).use { statement ->
            statement.setString(1, blindedId)
            statement.setBytes(2, envelope)
            statement.executeUpdate()
        }
    }

    /**
     * Destroys a row.
     *
     * Only `purgeNote` and `purgeFolder` reach this. An ordinary delete is a *record update* whose
     * payload carries the tombstone — the protocol has no delete — so removing a row is the one
     * operation that leaves another device holding a version this one no longer has. That is the
     * known resurrection hazard `docs/design/e2e-sync-phase3-plan.md` §5.4 names for the phone's
     * four hard `DELETE`s, and this store inherits it rather than inventing a different answer:
     * diverging from the phone here would mean two devices with different ideas of what "delete
     * forever" does.
     */
    fun remove(blindedId: String) {
        connection.prepareStatement("DELETE FROM records WHERE blinded_id = ?").use { statement ->
            statement.setString(1, blindedId)
            statement.executeUpdate()
        }
    }

    /**
     * Records that the server has accepted this device's version of [blindedId] at [seq].
     *
     * Unused until the sync engine lands; it is here because it is the other half of what `dirty`
     * and `last_synced_seq` are *for*, and a store that could only ever set `dirty = 1` would leave
     * the columns looking decorative.
     */
    fun markSynced(blindedId: String, seq: Long) {
        connection.prepareStatement(
            "UPDATE records SET dirty = 0, last_synced_seq = ? WHERE blinded_id = ?",
        ).use { statement ->
            statement.setLong(1, seq)
            statement.setString(2, blindedId)
            statement.executeUpdate()
        }
    }

    override fun close() = connection.close()
}
