package my.cheysoff.desktop.store

import java.nio.file.Path
import java.sql.Connection
import java.sql.DriverManager

/** One row of `records`, exactly as it sits on disk. */
data class StoredRecord(
    val blindedId: String,
    val envelope: ByteArray,
    /** True when this device holds a version the server has not acknowledged. */
    val dirty: Boolean,
    /** The `seq` the server last gave this record, or null if the server has no version of it. */
    val lastSyncedSeq: Long?,
    /**
     * The `content` clock of the newest version this device and the server agreed on, serialised,
     * or null when none is recorded.
     *
     * Null is legal and is the state of every row written before a sync ever ran. The merge reads
     * null as "fall back to the conservative conflict-copy rule", which converges and writes copies
     * it did not need — the phone's `contentSyncedHlc` stores `''` for exactly the same state and
     * its DAO gives the same reason for not parsing that into `Hlc.ZERO`.
     */
    val contentBaseline: String? = null,
) {
    // Generated by hand because `envelope` is an array: the data-class versions would compare it by
    // identity, so two rows read from the same table in two queries would never be equal. Nothing
    // depends on this today, and that is the problem -- an equality that is wrong only in the case
    // nobody has written yet is a bug waiting for its first caller.
    override fun equals(other: Any?): Boolean = other is StoredRecord &&
        blindedId == other.blindedId &&
        envelope.contentEquals(other.envelope) &&
        dirty == other.dirty &&
        lastSyncedSeq == other.lastSyncedSeq &&
        contentBaseline == other.contentBaseline

    override fun hashCode(): Int {
        var result = blindedId.hashCode()
        result = 31 * result + envelope.contentHashCode()
        result = 31 * result + dirty.hashCode()
        result = 31 * result + (lastSyncedSeq?.hashCode() ?: 0)
        result = 31 * result + (contentBaseline?.hashCode() ?: 0)
        return result
    }
}

/**
 * The desktop's local store: the server's table, on this machine.
 *
 * ```sql
 * records(blinded_id TEXT PRIMARY KEY, envelope BLOB, dirty INTEGER, last_synced_seq INTEGER)
 * ```
 *
 * That is the same shape `server/.../SyncStore.kt` holds, and holding it here rather than a
 * notes/folders schema is the design decision this whole module is built around. Two things follow
 * and both are the reason:
 *
 *  1. **At-rest security on desktop equals on-the-wire security.** A row is a `RecordEnvelope`:
 *     AES-256-GCM under a per-record key derived from `K_content`. Someone who copies `records.db`
 *     off the machine has exactly what the server operator has, and the server operator is the
 *     adversary this protocol was designed against. There is no SQLCipher here and none is needed;
 *     a file-level cipher would be a second, weaker layer over content that is already sealed.
 *  2. **The desktop is a sync replica by construction.** When the sync engine arrives it pushes
 *     these rows and stores what it pulls into these rows. Nothing translates between a local
 *     schema and a wire format, so there is no translation to get wrong -- and no second place
 *     where a field can be dropped.
 *
 * ## What it costs
 *
 * **No SQL over note content.** `WHERE title LIKE ?` is not expressible: the server cannot read
 * these rows and neither can SQLite. Search, sort and filter all happen in memory over decrypted
 * records, which is why [RecordNotesRepository] decrypts everything at unlock and serves reads from
 * a snapshot.
 *
 * **Everything is decrypted at unlock.** Opening the vault is O(number of records): one HKDF and
 * one AES-GCM open each, plus 4 KiB of padding stripped per record. Measured on the development
 * machine at roughly 30 microseconds per record, so a thousand notes is about 30 ms and ten
 * thousand about a third of a second — still under the threshold where a progress indicator is
 * needed. The memory cost is the sharper limit: every note's plaintext is resident for the whole
 * session, so ten thousand notes averaging 2 KB is around 20 MB of heap, and a hundred thousand is
 * 200 MB plus the padding overhead of reading them.
 *
 * **Where this stops being fine** is therefore somewhere around the tens of thousands of notes, and
 * the fix when it comes is not a different table: it is decrypting lazily and keeping an in-memory
 * index of just the fields the list screen shows. That change is local to
 * [RecordNotesRepository]; this class does not need to know.
 *
 * ## Threading
 *
 * One connection, and callers must serialise their own access — [RecordNotesRepository] does it
 * with a mutex. SQLite handles concurrent readers but this class deliberately does not hand out a
 * connection pool: the store is behind a repository whose writes are already serialised, and a pool
 * would only add a way for two writes to interleave.
 */
class RecordStore private constructor(private val connection: Connection) : AutoCloseable {

    companion object {
        /** Opens (creating if needed) the store at [path]. */
        fun open(path: Path): RecordStore {
            val store = RecordStore(DriverManager.getConnection("jdbc:sqlite:${path.toAbsolutePath()}"))
            store.migrate()
            return store
        }

        /**
         * An in-memory store, for tests.
         *
         * Named rather than `:memory:` so that the connection this returns is the only one that can
         * reach it; a plain `:memory:` database would be a fresh empty one for every connection,
         * which hides exactly the bugs a store test is looking for.
         */
        fun inMemory(name: String): RecordStore {
            val store = RecordStore(
                DriverManager.getConnection("jdbc:sqlite:file:$name?mode=memory&cache=shared"),
            )
            store.migrate()
            return store
        }
    }

    private fun migrate() {
        connection.createStatement().use { statement ->
            statement.executeUpdate(
                """
                CREATE TABLE IF NOT EXISTS records (
                    blinded_id TEXT PRIMARY KEY,
                    envelope BLOB NOT NULL,
                    dirty INTEGER NOT NULL,
                    last_synced_seq INTEGER
                )
                """.trimIndent(),
            )
            // Nullable, and NULL rather than 0 means "the server has no version of this record".
            // The phone spells the same state as 0 because its column is NOT NULL; the difference
            // is invisible to the protocol -- `seq` is the server's own counter and starts at 1 --
            // and NULL is the more honest spelling for a column that is genuinely absent.

            // Added rather than folded into the CREATE above, because a vault written before sync
            // existed already has the table and `CREATE TABLE IF NOT EXISTS` would leave it alone.
            // Guarded by reading the schema rather than by catching the duplicate-column error: a
            // swallowed SQLException here would also swallow a disk failure.
            if (!hasColumn("records", "content_baseline")) {
                statement.executeUpdate("ALTER TABLE records ADD COLUMN content_baseline TEXT")
            }

            // One row, keyed by account, for the same reason `SyncStateEntity` on the phone is:
            // a cursor from another account is ahead of nothing, so pulling with it skips that
            // account's whole history and leaves the device convinced it is up to date.
            statement.executeUpdate(
                """
                CREATE TABLE IF NOT EXISTS sync_state (
                    account_id TEXT PRIMARY KEY,
                    cursor INTEGER NOT NULL,
                    halt TEXT
                )
                """.trimIndent(),
            )
        }
    }

    private fun hasColumn(table: String, column: String): Boolean =
        connection.createStatement().use { statement ->
            statement.executeQuery("PRAGMA table_info($table)").use { results ->
                generateSequence { if (results.next()) results.getString("name") else null }
                    .any { it == column }
            }
        }

    /** Every row. The only read: a session decrypts all of them at unlock. */
    fun readAll(): List<StoredRecord> {
        val rows = mutableListOf<StoredRecord>()
        connection.createStatement().use { statement ->
            statement.executeQuery(
                "SELECT blinded_id, envelope, dirty, last_synced_seq, content_baseline FROM records",
            ).use { results ->
                while (results.next()) {
                    val blindedId = results.getString(1)
                    val envelope = results.getBytes(2)
                    val dirty = results.getInt(3) != 0
                    val seq = results.getLong(4)
                    // `wasNull()` reports on the column read LAST, so it has to be asked
                    // immediately after `getLong(4)` and not after any other read. JDBC returns 0
                    // for a SQL NULL, and 0 versus "the server has no version of this record" are
                    // different states here.
                    val lastSyncedSeq = if (results.wasNull()) null else seq
                    rows += StoredRecord(
                        blindedId, envelope, dirty, lastSyncedSeq, results.getString(5),
                    )
                }
            }
        }
        return rows
    }

    /**
     * Inserts or replaces the record [blindedId], marking it dirty.
     *
     * `last_synced_seq` is left alone on an update, and that is the same rule `NoteDao.upsertNote`
     * follows for the same reason: it is the baseline the next push is built on, and resetting it
     * would tell the server that an already-uploaded record must not exist.
     */
    fun put(blindedId: String, envelope: ByteArray) {
        connection.prepareStatement(
            """
            INSERT INTO records (blinded_id, envelope, dirty, last_synced_seq)
            VALUES (?, ?, 1, NULL)
            ON CONFLICT(blinded_id) DO UPDATE SET envelope = excluded.envelope, dirty = 1
            """.trimIndent(),
        ).use { statement ->
            statement.setString(1, blindedId)
            statement.setBytes(2, envelope)
            statement.executeUpdate()
        }
    }

    /**
     * Destroys a row.
     *
     * Only `purgeNote` and `purgeFolder` reach this. An ordinary delete is a *record update* whose
     * payload carries the tombstone — the protocol has no delete — so removing a row is the one
     * operation that leaves another device holding a version this one no longer has. That is the
     * known resurrection hazard `docs/design/e2e-sync-phase3-plan.md` §5.4 names for the phone's
     * four hard `DELETE`s, and this store inherits it rather than inventing a different answer:
     * diverging from the phone here would mean two devices with different ideas of what "delete
     * forever" does.
     */
    fun remove(blindedId: String) {
        connection.prepareStatement("DELETE FROM records WHERE blinded_id = ?").use { statement ->
            statement.setString(1, blindedId)
            statement.executeUpdate()
        }
    }

    /** One row, or null. The sync store's read path; the repository still reads everything. */
    fun read(blindedId: String): StoredRecord? {
        connection.prepareStatement(
            "SELECT envelope, dirty, last_synced_seq, content_baseline FROM records " +
                "WHERE blinded_id = ?",
        ).use { statement ->
            statement.setString(1, blindedId)
            statement.executeQuery().use { results ->
                if (!results.next()) return null
                val envelope = results.getBytes(1)
                val dirty = results.getInt(2) != 0
                val seq = results.getLong(3)
                val lastSyncedSeq = if (results.wasNull()) null else seq
                return StoredRecord(blindedId, envelope, dirty, lastSyncedSeq, results.getString(4))
            }
        }
    }

    /**
     * Runs [block] inside one database transaction, committing at the end and rolling back if it
     * throws.
     *
     * There is exactly one operation that needs this, and it is not a performance concern: applying
     * a merge that produced a **conflict copy** writes two rows — the merged record, which takes
     * the winning body, and the copy, which is the only remaining home of the losing one. Written
     * separately, a crash between them leaves the winner stored and the loser gone, which is
     * precisely the outcome conflict copies exist to prevent. Either both rows land or neither
     * does.
     *
     * Nested calls are not supported; nothing here needs them, and SQLite has no nested
     * transactions without savepoints.
     */
    fun <T> inTransaction(block: () -> T): T {
        val previous = connection.autoCommit
        connection.autoCommit = false
        try {
            val result = block()
            connection.commit()
            return result
        } catch (e: Throwable) {
            // Rolled back on ANY throwable, not just SQLException: a failure inside `block` that is
            // not the database's fault (a codec refusing to seal, say) leaves the transaction just
            // as half-written, and a half-applied merge is the thing worth preventing.
            connection.rollback()
            throw e
        } finally {
            connection.autoCommit = previous
        }
    }

    /**
     * Writes a record the sync engine decided on: the envelope and all three bookkeeping columns,
     * in one statement.
     *
     * Distinct from [put], which is the *local edit* path and deliberately sets `dirty = 1` and
     * leaves `last_synced_seq` alone. A merge decides all four values together, and writing them
     * through two calls would leave a window in which a merged row carries the previous version's
     * `lastSyncedSeq` — a row that takes a guaranteed `409` on every subsequent pass, forever.
     */
    fun writeMerged(
        blindedId: String,
        envelope: ByteArray,
        dirty: Boolean,
        lastSyncedSeq: Long?,
        contentBaseline: String?,
    ) {
        connection.prepareStatement(
            """
            INSERT INTO records (blinded_id, envelope, dirty, last_synced_seq, content_baseline)
            VALUES (?, ?, ?, ?, ?)
            ON CONFLICT(blinded_id) DO UPDATE SET
                envelope = excluded.envelope,
                dirty = excluded.dirty,
                last_synced_seq = excluded.last_synced_seq,
                content_baseline = excluded.content_baseline
            """.trimIndent(),
        ).use { statement ->
            statement.setString(1, blindedId)
            statement.setBytes(2, envelope)
            statement.setInt(3, if (dirty) 1 else 0)
            if (lastSyncedSeq == null) statement.setNull(4, java.sql.Types.INTEGER)
            else statement.setLong(4, lastSyncedSeq)
            statement.setString(5, contentBaseline)
            statement.executeUpdate()
        }
    }

    /**
     * Records that this device has now **seen** server version [seq] of [blindedId], without
     * touching the record itself.
     *
     * The row's data must not move — the merge decided nothing had to change — while its
     * `last_synced_seq` must, because the next push has to be built on the version the server
     * actually holds. `SyncStore.recordSeen` explains why splitting this from the merged write is
     * not tidiness.
     */
    fun markSeen(blindedId: String, seq: Long, contentBaseline: String?) {
        connection.prepareStatement(
            "UPDATE records SET last_synced_seq = ?, content_baseline = ? WHERE blinded_id = ?",
        ).use { statement ->
            statement.setLong(1, seq)
            statement.setString(2, contentBaseline)
            statement.setString(3, blindedId)
            statement.executeUpdate()
        }
    }

    /**
     * §3.2's two rules for an accepted push, as one statement.
     *
     * `dirty` is cleared **only if** the stored envelope is still the one that was sent, and
     * `last_synced_seq` is written **either way**. The phone expresses the same guard as
     * `WHERE hlcMs = :sealedMs AND hlcCounter = :sealedCounter`; here the row clock is inside the
     * sealed envelope and cannot be compared in SQL, so the caller passes the exact bytes it sent
     * and the comparison is on those. It is the stronger of the two comparisons — a record whose
     * clock is unchanged but whose body moved would satisfy the phone's guard and not this one —
     * and it is the same event either way: the user edited the note while the push was in flight,
     * and clearing `dirty` would drop that edit with no error and no way to notice.
     */
    fun acknowledgePush(
        blindedId: String,
        sentEnvelope: ByteArray,
        seq: Long,
        contentBaseline: String?,
    ) {
        connection.prepareStatement(
            "UPDATE records SET last_synced_seq = ?, content_baseline = ?, " +
                "dirty = CASE WHEN envelope = ? THEN 0 ELSE dirty END WHERE blinded_id = ?",
        ).use { statement ->
            statement.setLong(1, seq)
            statement.setString(2, contentBaseline)
            statement.setBytes(3, sentEnvelope)
            statement.setString(4, blindedId)
            statement.executeUpdate()
        }
    }

    /** The server `seq` this device has pulled up to on [accountId], or 0 before the first pull. */
    fun cursor(accountId: String): Long =
        connection.prepareStatement("SELECT cursor FROM sync_state WHERE account_id = ?")
            .use { statement ->
                statement.setString(1, accountId)
                statement.executeQuery().use { if (it.next()) it.getLong(1) else 0L }
            }

    /**
     * Moves the cursor forward. **Forwards only, and the guard is in the SQL.**
     *
     * The engine never calls this with a seq below the stored one, so the guard is not for the
     * engine; it is for the next caller. A cursor that went backwards would replay the account,
     * and one that went backwards *silently* would do it on a device the user is watching.
     */
    fun saveCursor(accountId: String, seq: Long) {
        connection.prepareStatement(
            "INSERT INTO sync_state (account_id, cursor, halt) VALUES (?, ?, NULL) " +
                "ON CONFLICT(account_id) DO UPDATE SET cursor = MAX(cursor, excluded.cursor)",
        ).use { statement ->
            statement.setString(1, accountId)
            statement.setLong(2, seq)
            statement.executeUpdate()
        }
    }

    /** The stored halt reason for [accountId], or null while the engine is healthy. */
    fun halt(accountId: String): String? =
        connection.prepareStatement("SELECT halt FROM sync_state WHERE account_id = ?")
            .use { statement ->
                statement.setString(1, accountId)
                statement.executeQuery().use { if (it.next()) it.getString(1) else null }
                    ?.takeIf { it.isNotEmpty() }
            }

    /**
     * Records a halt. Idempotent, keeping the **first** reason — the guard is in the SQL.
     *
     * The first reason is the one that explains the rest: a rolled-back server produces a stream of
     * consequences, and overwriting the cause with the last of its symptoms is how a diagnosable
     * state becomes a confusing one.
     */
    fun recordHalt(accountId: String, reason: String) {
        connection.prepareStatement(
            "INSERT INTO sync_state (account_id, cursor, halt) VALUES (?, 0, ?) " +
                "ON CONFLICT(account_id) DO UPDATE SET halt = COALESCE(sync_state.halt, excluded.halt)",
        ).use { statement ->
            statement.setString(1, accountId)
            statement.setString(2, reason)
            statement.executeUpdate()
        }
    }

    override fun close() = connection.close()
}
