package my.cheysoff.feature_pairing.identity

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import my.cheysoff.feature_pairing.protocol.P256
import java.security.KeyPairGenerator
import java.security.KeyStore
import java.security.PrivateKey
import java.security.Signature
import java.security.interfaces.ECPublicKey
import java.security.spec.ECGenParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * The device's long-lived signing identity: one EC P-256 key pair in the AndroidKeyStore, created
 * once and never exported.
 *
 * ## What it is for
 *
 * Nothing on this branch uses it to sign anything — pairing itself needs no signature, because the
 * QR exchange authenticates itself by a human looking at a screen. It is provisioned *during*
 * pairing because that is the only moment at which a device joins an account, and Phase 3's server
 * contract is built on it: an already-enrolled device vouches for a new one by signing
 * `("authorize", accountId, newPubKey, ts)`, and session tokens are obtained by signing a
 * server challenge. The server therefore ends up holding a set of public keys and no secrets at
 * all.
 *
 * Creating it here rather than in Phase 3 means the key exists from the moment the device has an
 * account, instead of being minted lazily on a device that may by then be offline.
 *
 * ## Why EC P-256 and `SHA256withECDSA`
 *
 * The same reason the pairing ECDH is P-256: Keystore support for Ed25519 (`KeyProperties`'
 * `KEY_ALGORITHM_EC` with the Ed25519 curve, and the `EdECKey` interfaces) begins at API 33, and
 * this app's floor is 31. P-256 in the Keystore has been available since API 23. One algorithm,
 * one code path, no runtime version branch.
 *
 * ## Authentication
 *
 * The key is deliberately **not** created with `setUserAuthenticationRequired(true)`. That is a
 * real trade-off and it is worth being explicit about it: a thief holding an unlocked phone could
 * make this key sign. What that buys them is Phase-3 ciphertext from the user's own server, which
 * is useless without the ARK — and the ARK is wrapped under the database passphrase, which lives
 * in memory only between an unlock and the next re-lock. What requiring authentication would cost
 * is the ability to sync in the background at all, which is precisely the door the architecture
 * document leaves open for Phase 5. If that door is ever closed, this decision should be revisited
 * along with it.
 *
 * ## Hardware backing
 *
 * `setIsStrongBoxBacked` is not requested. StrongBox is absent on many devices and a request for it
 * fails the whole generation with `StrongBoxUnavailableException`, which would mean a fallback path
 * and two possible key provenances for no gain here — the threat this key defends against is a
 * server compromise, not physical extraction.
 */
@Singleton
class DeviceIdentityKey @Inject constructor() : DeviceIdentity {

    override fun ensureProvisioned(): ByteArray = encodedPublicKey()

    override fun isProvisioned(): Boolean = exists()

    /**
     * Return the device's public identity key, generating the pair on first call.
     *
     * Idempotent: the second and every later call load the existing entry. That "created in exactly
     * one place, and only if absent" discipline is the same one `SecureUnlockManager.setupPin`
     * follows, and for the same reason — a key regenerated by accident silently invalidates every
     * signature the old one made.
     */
    fun publicKey(): ECPublicKey {
        val store = loadKeyStore()
        val existing = store.getCertificate(ALIAS)?.publicKey as? ECPublicKey
        if (existing != null) return existing
        return generate()
    }

    /** The public key in the SEC1 uncompressed form the rest of this module speaks. */
    fun encodedPublicKey(): ByteArray = P256.encodePublicKey(publicKey())

    /**
     * Sign [data] with the device key.
     *
     * Present for Phase 3 rather than used here. It is included now because a signing key that has
     * never been exercised is a key nobody has confirmed is usable, and the failure mode of
     * discovering that later is a device that pairs successfully and then cannot enrol.
     */
    fun sign(data: ByteArray): ByteArray {
        val store = loadKeyStore()
        val privateKey = store.getKey(ALIAS, null) as? PrivateKey
            ?: throw IllegalStateException("no device identity key; call publicKey() first")
        return Signature.getInstance(SIGNATURE_ALGORITHM).run {
            initSign(privateKey)
            update(data)
            sign()
        }
    }

    /** True once the key exists. Never generates. */
    fun exists(): Boolean = loadKeyStore().containsAlias(ALIAS)

    private fun generate(): ECPublicKey {
        val generator = KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_EC, PROVIDER)
        generator.initialize(
            KeyGenParameterSpec.Builder(ALIAS, KeyProperties.PURPOSE_SIGN or KeyProperties.PURPOSE_VERIFY)
                .setAlgorithmParameterSpec(ECGenParameterSpec(CURVE))
                .setDigests(KeyProperties.DIGEST_SHA256)
                // No setUserAuthenticationRequired -- see the class comment.
                .build()
        )
        return generator.generateKeyPair().public as ECPublicKey
    }

    private fun loadKeyStore(): KeyStore =
        KeyStore.getInstance(PROVIDER).apply { load(null) }

    private companion object {
        const val PROVIDER = "AndroidKeyStore"
        const val ALIAS = "manana_device_identity_v1"
        const val CURVE = "secp256r1"
        const val SIGNATURE_ALGORITHM = "SHA256withECDSA"
    }
}
