package my.cheysoff.core_crypto

import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyPermanentlyInvalidatedException
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Provides the biometric-gated Android Keystore key and the initialized [Cipher] objects to hand
 * to `BiometricPrompt.CryptoObject`.
 *
 * The key ([KEY_ALIAS]) is AES-256-GCM, requires user authentication, and uses per-use
 * authentication (a fresh biometric auth unlocks the cipher for a single crypto operation). It is
 * also invalidated when biometrics are re-enrolled, so a re-enrollment forces the caller to drop
 * the biometric wrap and fall back to PIN.
 *
 * This class only provisions the key and returns *initialized* ciphers. The actual
 * `doFinal` (encrypting/decrypting the DB passphrase) runs in Task A3 with the *unlocked* cipher
 * returned by the biometric prompt.
 *
 * Device-level (Android Keystore) — not exercisable in plain JVM unit tests. Never logs secrets.
 */
@Singleton
class BiometricKeystoreCipher @Inject constructor() {

    private val keyStore: KeyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    /** True if the biometric Keystore key has been provisioned. */
    fun hasKey(): Boolean = keyStore.containsAlias(KEY_ALIAS)

    /**
     * Create the key if absent and return an ENCRYPT-mode [Cipher] to put in a `CryptoObject`
     * (for enabling biometric). Its IV is generated by the provider during init — read
     * `cipher.iv` after the prompt succeeds and persist it for later decryption.
     */
    fun createEncryptCipher(): Cipher {
        if (!hasKey()) {
            generateKey()
        }
        val cipher = Cipher.getInstance(CIPHER_TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        return cipher
    }

    /**
     * DECRYPT-mode [Cipher] initialized for the stored [iv] (for unlocking).
     *
     * Throws [KeyPermanentlyInvalidatedException] if biometrics were re-enrolled since the key was
     * created — the caller should drop the biometric wrap and fall back to PIN. The exception is
     * intentionally allowed to propagate.
     */
    fun createDecryptCipher(iv: ByteArray): Cipher {
        val cipher = Cipher.getInstance(CIPHER_TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(TAG_BITS, iv))
        return cipher
    }

    /** Delete the Keystore key (e.g. user disables biometric, or it was invalidated). */
    fun deleteKey() {
        keyStore.deleteEntry(KEY_ALIAS)
    }

    private fun secretKey(): SecretKey = keyStore.getKey(KEY_ALIAS, null) as SecretKey

    private fun generateKey() {
        val builder = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(KEY_SIZE_BITS)
            .setUserAuthenticationRequired(true)
            .setInvalidatedByBiometricEnrollment(true)

        // Per-use authentication: every crypto operation requires a fresh biometric auth.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            builder.setUserAuthenticationParameters(0, KeyProperties.AUTH_BIOMETRIC_STRONG)
        } else {
            @Suppress("DEPRECATION")
            builder.setUserAuthenticationValidityDurationSeconds(-1)
        }

        val keyGenerator =
            KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        keyGenerator.init(builder.build())
        keyGenerator.generateKey()
    }

    private companion object {
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val KEY_ALIAS = "manana_db_bio"
        const val CIPHER_TRANSFORMATION = "AES/GCM/NoPadding"
        const val KEY_SIZE_BITS = 256
        const val TAG_BITS = 128
    }
}
